# Generated by Django 4.2.5 on 2024-01-14 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
    ]
