# Generated by Django 4.2.5 on 2024-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location_image2',
            field=models.ImageField(default='image_not_found.jpg', upload_to='location'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location_image3',
            field=models.ImageField(default='image_not_found.jpg', upload_to='location'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location_image4',
            field=models.ImageField(default='image_not_found.jpg', upload_to='location'),
        ),
    ]
