# Generated by Django 4.2.5 on 2024-01-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_alter_product_seller'),
        ('store', '0008_alter_store_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='store', to='catalogue.product'),
        ),
    ]
