# Generated by Django 4.2.5 on 2024-02-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_store_products_remove_store_staff_storerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerecord',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
