# Generated by Django 4.2.5 on 2024-02-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('all-in-one', 'All in One')], default='all-in-one', max_length=20),
        ),
    ]
