# Generated by Django 4.2.5 on 2024-02-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='type',
        ),
        migrations.AddField(
            model_name='store',
            name='product_type',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('all-in-one', 'All in One')], default='all-in-one', help_text='The kind of products the store has', max_length=20),
        ),
    ]
