# Generated by Django 4.2.5 on 2024-02-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_store_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_type',
            field=models.CharField(choices=[('none', 'None'), ('fashion', 'Fashion'), ('electronics', 'Electronics')], default='none', help_text='The kind of products your store has', max_length=20),
        ),
    ]
