# Generated by Django 4.2.5 on 2024-02-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_store_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_type',
            field=models.CharField(choices=[('all-in-one', 'All in One store'), ('fashion', 'Fashion store'), ('electronics', 'Electronics store')], default='all-in-one', help_text='The kind of products your store deals in', max_length=20),
        ),
    ]
