# Generated by Django 4.2.5 on 2024-03-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_productclass_category'),
        ('store', '0027_alter_store_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product_type',
        ),
        migrations.AddField(
            model_name='store',
            name='product_type',
            field=models.ManyToManyField(to='catalogue.category'),
        ),
    ]
