# Generated by Django 4.2.5 on 2024-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_data_viewed_userstorerecord_date_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorerecord',
            name='recently_viewd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
