# Generated by Django 4.2.5 on 2024-03-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_recently_viewd_userstorerecord_recently_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstorerecord',
            old_name='recently_viewed',
            new_name='last_viewed',
        ),
    ]
