# Generated by Django 4.2.5 on 2024-03-12 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0033_rename_recently_viewed_userstorerecord_last_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerecord',
            name='followers',
        ),
        migrations.CreateModel(
            name='FollowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_followed', models.DateTimeField(auto_now_add=True)),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_store', to=settings.AUTH_USER_MODEL)),
                ('store_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storerecord')),
            ],
        ),
        migrations.AddField(
            model_name='storerecord',
            name='store_followers',
            field=models.ManyToManyField(through='store.FollowInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
