# Generated by Django 4.2.5 on 2024-03-15 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0035_rename_data_followed_followinfo_date_followed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-delta_votes', 'id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='delta_votes',
            field=models.IntegerField(default=0, verbose_name='Delta Votes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='total_votes',
            field=models.IntegerField(default=0, verbose_name='Total votes'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')], verbose_name='Delta')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='store.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Vote',
                'verbose_name_plural': 'Comment Votes',
                'ordering': ['-date_created'],
            },
        ),
    ]
