# Generated by Django 4.2.5 on 2024-03-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_store_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='prompted',
        ),
    ]
