# Generated by Django 4.2.5 on 2023-11-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staticimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticImages',
            new_name='StaticImage',
        ),
    ]
