# Generated by Django 4.2.5 on 2024-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
