# Generated by Django 4.2.5 on 2024-01-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticImage',
        ),
    ]
