# Generated by Django 4.2.5 on 2024-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_has_accepted_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
