# Generated by Django 4.2.5 on 2024-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_staticimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='loation',
            field=models.CharField(choices=[('BW', 'Bweyale'), ('KY', 'Kyradongo')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='blank-profile.png', upload_to='profiles'),
        ),
    ]
