# Generated by Django 4.2.5 on 2024-01-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_referral_code_user_referral_url_user_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.TextField(max_length=6, unique=True),
        ),
    ]
