# Generated by Django 4.2.5 on 2023-11-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_user_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
