# Generated by Django 4.2.5 on 2023-11-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_staticimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticImages',
        ),
    ]
