# Generated by Django 4.2.5 on 2024-02-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_productclass_category'),
        ('analytics', '0003_auto_20200801_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.category'),
        ),
    ]
